name: HEMnet 
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - astor=0.7.1
  - automake=1.16.1
  - bzip2=1.0.6
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cmake=3.12.2
  - cytoolz=0.9.0.1
  - expat=2.2.6
  - gast=0.2.2
  - intel-openmp=2019.4
  - joblib=0.13.2
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libxml2=2.9.9
  - markdown=3.1.1
  - mkl=2019.4
  - olefile=0.46
  - openssl=1.1.1
  - patsy=0.5.1
  - pkg-config=0.29.2
  - pkgconfig=1.4.0
  - python-dateutil=2.8.0
  - pywavelets=1.0.3
  - scikit-image=0.15.0
  - seaborn=0.9.0
  - six=1.12.0
  - tensorflow-estimator=1.13.0
  - toolz=0.9.0
  - zstd=1.3.7
  - absl-py=0.7.1
  - asn1crypto=1.0.1
  - atk=2.32.0
  - attrs=19.1.0
  - autoconf=2.69
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - cairo=1.16.0
  - cffi=1.12.3
  - chardet=3.0.4
  - cloudpickle=1.1.1
  - colorama=0.4.1
  - cryptography=2.7
  - cycler=0.10.0
  - dask-core=1.2.2
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gdk-pixbuf=2.36.12
  - gettext=0.19.8.1
  - gitdb2=2.0.6
  - gitpython=3.0.3
  - glib=2.58.3
  - gobject-introspection=1.58.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtk2=2.24.31
  - h5py=2.9.0
  - harfbuzz=2.4.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - jupyterlab=0.35.6
  - jupyterlab_server=0.2.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - libjpeg-turbo=2.0.2
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - lz4-c=1.8.3
  - m4=1.4.18
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mistune=0.8.4
  - mock=3.0.5
  - nbconvert=5.5.0
  - nbdime=1.1.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - nodejs=12.4.0
  - notebook=5.7.8
  - numpy=1.16.4
  - openjpeg=2.3.1
  - pandas=0.24.2
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso=0.4.0
  - pcre=8.41
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - pixman=0.34.0
  - prometheus_client=0.7.0
  - prompt_toolkit=2.0.9
  - protobuf=3.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.15.2
  - pysocks=1.7.1
  - python=3.6.7
  - python-spams=2.6.1
  - pytz=2019.1
  - pyyaml=5.1.1
  - pyzmq=18.0.1
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - rhash=1.3.6
  - scipy=1.3.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - smmap2=2.0.5
  - sqlite=3.28.0
  - statsmodels=0.10.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - tqdm=4.33.0
  - traitlets=4.3.2
  - urllib3=1.25.6
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - grpcio=1.16.1
  - mkl-service=2.0.2
  - pillow=6.2.1
  - scikit-learn=0.21.2


